In [5]:
import numpy as np
liste=[10,20,30,40,50]
dizi=np.array(liste)
dizi
dizi.dtype

dtype('int32')

In [8]:
karisik_liste = [1, 2, 3.5]
karisik=np.array(karisik_liste)
karisik.dtype


dtype('float64')

In [16]:
import numpy as np
matris=np.array([[1,2,3],[4,5,6]])
print(matris)
print("boyut sayisi:",matris.ndim)
print("şekil (satur sutun,sayısı)",matris.shape)

[[1 2 3]
 [4 5 6]]
boyut sayisi: 2
şekil (satur sutun,sayısı) (2, 3)


In [39]:
import numpy as np
sayilar = np.arange(10, 50, 2)
cift=(sayilar%2==0)
sonuc=sayilar[cift]
sonuc

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [40]:
import numpy as np

# 3x3'lük sıfır matrisi (Tam sayı olsun istiyoruz)
sifirlar = np.zeros((3, 3), dtype=int)

# 0 ile 10 arasında 5 tane eşit aralıklı sayı üret
# (0, 2.5, 5, 7.5, 10 gibi)
esit_aralik = np.linspace(0, 10, 5)

# 10'dan 50'ye kadar 5'er 5'er say
sayilar = np.arange(10, 50, 5)

print("Sıfırlar:\n", sifirlar)
print("Linspace:", esit_aralik)
print("Arange:", sayilar)

Sıfırlar:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]
Linspace: [ 0.   2.5  5.   7.5 10. ]
Arange: [10 15 20 25 30 35 40 45]


#Kritik Kavram: Eksenler (Axis)
axis=0: Sütunlar boyunca işlem yapar (Yukarıdan aşağıya).

axis=1: Satırlar boyunca işlem yapar (Soldan sağa).

In [45]:
# Bellek dostu dizi oluşturma
dizi_float = np.array([1.5, 2.5], dtype=np.float16)
dizi_float.dtype

dtype('float16')

In [52]:
import numpy as np
dizi=np.array([[1,2,3],[4,5,6]],dtype=np.float32)
dizi.shape
dizi


array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [53]:
import numpy as np
dizi=np.array([[1,2,3],[4,5,6]],dtype=np.float32)
dizi.size #içerideki toplam eleman sayısını verir.

6

In [59]:
dizi=np.arange(10,50,5)
print(dizi)
dizi2=np.linspace(0,1,5)
print(dizi2)

[10 15 20 25 30 35 40 45]
[0.  0.2 0.4 0.6 0.8 1. ]


In [65]:
# 8 elemanlı diziyi oluşturup anında 2 satır, 4 sütunlu bir matrise çevirmek
dizi_matris = np.arange(10, 50, 5).reshape(4,2)
dizi_matris

array([[10, 15],
       [20, 25],
       [30, 35],
       [40, 45]])

In [76]:
np.random.seed(42)
rastgele_ondalik=np.random.randn(2,2)

rastgele_normal = np.random.randn(3, 3)
rastgele_normal

array([[-0.23415337, -0.23413696,  1.57921282],
       [ 0.76743473, -0.46947439,  0.54256004],
       [-0.46341769, -0.46572975,  0.24196227]])

In [101]:
import numpy as np
np.random.seed(42)
sayi_dizisi=np.random.randint(1,50,size=(5,5))
sayi_dizisi

array([[39, 29, 15, 43,  8],
       [21, 39, 19, 23, 11],
       [11, 24, 36, 40, 24],
       [ 3, 22,  2, 24, 44],
       [30, 38,  2, 21, 33]])

In [2]:
import numpy as np

dizi1=np.array([1,2,3])
dizi2=np.array([10,20,30])

yeni_dizi1=dizi1+5
yeni_dizi1

array([6, 7, 8])

In [6]:
import numpy as np

np.random.seed(42)

matris=np.arange(1,10).reshape(3,3)
matris **=2
matris-=10
matris

array([[-9, -6, -1],
       [ 6, 15, 26],
       [39, 54, 71]])

In [11]:
import numpy as np

notlar = np.array([[50, 60],  # 1. Öğrencinin Vize ve Finali
                   [70, 80],  # 2. Öğrencinin Vize ve Finali
                   [90, 100]]) # 3. Öğrencinin Vize ve Finali

# Tüm sınıftaki tüm notların genel ortalaması (Eksen belirtmezsek hepsini tek bir dizi gibi düşünür)
genel_ortalama = notlar.mean() 

sinav_ortalamalari = notlar.mean(axis=0)
sinav_ortalamalari

ogrenci_bazli=notlar.mean(axis=1,keepdims=True)
ogrenci_bazli

array([[55.],
       [75.],
       [95.]])

In [16]:
satislar = np.array([[100, 50, 20],
                     [120, 60, 30],
                     [ 90, 40, 10]])

satis_top=satislar.sum().copy()
print(satis_top)

gun_bazli=satislar.sum(axis=0,keepdims=True)
print(gun_bazli)

520
[[310 150  60]]


In [2]:
import numpy as np
yaslar=np.array([1,2,3,4,56,21])

yetiskinler=yaslar[yaslar>19]
yetiskinler

array([56, 21])

In [27]:
import numpy as np
np.random.seed(42)
test_sonuclari=np.random.randint(0,100,size=(4,5)).copy()
gecen_notlar=test_sonuclari[test_sonuclari>50]
gecen_notlar+=10
gecen_notlar.mean()
test_sonuclari.mean()


53.1